services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${SQL_USER:-postgres}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-postgres}
      POSTGRES_DB: ${SQL_DB:-api}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${SQL_USER:-postgres}"]
      interval: 5s
      retries: 5
      timeout: 10s
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}

  migrator:
    image: brownhounds/migoro:0.1.0
    env_file:
      - ./api/.env
    environment:
      - SQL_HOST=postgres
    volumes:
      - ./api/migrations:/migrations
    command: migrate
    depends_on:
      postgres:
        condition: service_healthy

  api:
    build:
      context: ./api
    env_file:
      - ./api/.env
    environment:
      - SQL_HOST=postgres
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - 8080:8080

  app:
    build:
      context: ./app
    environment:
      - PORT=3000
      - IS_SPA=true
      - SPA_ENTRYPOINT=index.html
      - STATIC_FOLDER=/app
      - PUBLIC_PATH=/
    ports:
      - 3000:3000
