openapi: 3.0.0
info:
  title: Library Api
  description: Library Api
  version: 0.1.0

paths:
  /v1/auth/login:
    post:
      summary: Login endpoint
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: The user's email address
                password:
                  type: string
                  description: The user's password
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
        500:
          $ref: "#/components/responses/InternalServerError"
        400:
          $ref: "#/components/responses/BadRequest"

  /v1/auth/whoami:
    get:
      summary: Retrieve user information
      tags:
        - Authentication
      description: Get the current user's details including name, email, and avatar.
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful response with user details
          content:
            application/json:
              schema:
                type: object
                properties:
                  Name:
                    type: string
                    example: "Jon Doe"
                  Email:
                    type: string
                    example: "jon.doe@test.com"
                  Avatar:
                    type: string
                    format: uri
                    example: "https://mighty.tools/mockmind-api/content/human/7.jpg"
        500:
          $ref: "#/components/responses/InternalServerError"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"

  /v1/books:
    get:
      summary: Get a list of books
      tags:
        - Books
      responses:
        200:
          description: A list of books
          security:
            - bearerAuth: []
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Id:
                      $ref: "#/components/schemas/uuid"
                    Title:
                      type: string
                      example: "Frankenstein"
                    Author:
                      type: string
                      example: "Mary Shelley"
                    PublicationYear:
                      type: string
                      example: "1818"
                    Genres:
                      type: array
                      items:
                        type: string
                      example:
                        - "Science Fiction"
                        - "Gothic"
        500:
          $ref: "#/components/responses/InternalServerError"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"

  /v1/books/{id}:
    get:
      summary: Get book details by ID
      security:
        - bearerAuth: []
      tags:
        - Books
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the book
          schema:
            $ref: "#/components/schemas/uuid"
      responses:
        200:
          description: Successfully retrieved book details
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    $ref: "#/components/schemas/uuid"
                  Title:
                    type: string
                    example: Moby-Dick
                  Author:
                    type: string
                    example: Herman Melville
                  PublicationYear:
                    type: string
                    example: 1851
                  Description:
                    type: string
                  CoverImage:
                    type: string
                    format: uri
                  Genres:
                    type: array
                    items:
                      type: string
                    example:
                      - Fiction
                      - Adventure
                  UpdatedAt:
                    type: string
                    format: date-time
                    example: "2024-07-19T18:16:35.245139Z"
                  CreatedAt:
                    type: string
                    format: date-time
                    example: "2024-07-19T18:16:35.245139Z"
        500:
          $ref: "#/components/responses/InternalServerError"
        404:
          $ref: "#/components/responses/NotFound"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: uuid

  schemas:
    error:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          example: 400
        message:
          type: string

    uuid:
      type: string
      format: uuid
      example: "2f358541-2bba-4c25-b187-52de3039179f"

  responses:
    Forbidden:
      description: Access Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"

    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"

    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
